USE WAREHOUSE WH_INGEST;
USE DATABASE SEC_PRICING;

SELECT * FROM RAW.RAW_EOD_PRICES LIMIT 5;

MERGE INTO CORE.EOD_PRICES TGT
USING (WITH SRC_RAW AS (
    SELECT 
        R.TRADE_DATE,
        UPPER(TRIM(R.SYMBOL)) AS SYMBOL,
        R.OPEN, R.HIGH, R.LOW, R.CLOSE, R.VOLUME,
        R._INGEST_TS,
        R._SRC_FILE
    FROM RAW.RAW_EOD_PRICES AS R
),
RANKED AS (
    SELECT 
    TRADE_DATE, SYMBOL, OPEN, HIGH, LOW, CLOSE, VOLUME, _INGEST_TS, _SRC_FILE,
    ROW_NUMBER() OVER(
        PARTITION BY SYMBOL, TRADE_DATE
        ORDER BY _INGEST_TS DESC, _SRC_FILE DESC
    ) AS RN
    FROM SRC_RAW
)
SELECT TRADE_DATE, SYMBOL, OPEN, HIGH, LOW, CLOSE, VOLUME
FROM RANKED 
WHERE RN = 1
) SRC
ON UPPER(TRIM(TGT.SYMBOL)) = SRC.SYMBOL
AND TGT.TRADE_DATE = SRC.TRADE_DATE
WHEN MATCHED THEN UPDATE SET
OPEN = SRC.OPEN,
HIGH = SRC.HIGH,
LOW = SRC.LOW,
CLOSE = SRC.CLOSE,
VOLUME = SRC.VOLUME,
LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT(
    TRADE_DATE, SYMBOL, OPEN, HIGH, LOW, CLOSE, VOLUME, LOAD_TS
) VALUES (
SRC.TRADE_DATE, SRC.SYMBOL, SRC.OPEN, SRC.HIGH, SRC.LOW, SRC.CLOSE, SRC.VOLUME, CURRENT_TIMESTAMP()
);


Select Count(*) From SEC_PRICING.CORE.EOD_PRICES;
SELECT * FROM SEC_PRICING.CORE.EOD_PRICES;


-- 2) Build/maintain DM_DIM.DIM_SECURITY Purpose:
-- One row per SYMBOL
-- Only inserts new symbols observed in CORE

MERGE INTO DM_DIM.DIM_SECURITY AS D
USING (
    SELECT 
        SYMBOL,
        ROW_NUMBER() OVER (ORDER BY SYMBOL) AS EXPECTED_ID
    FROM (
        SELECT DISTINCT SYMBOL
        FROM CORE.EOD_PRICES
    )
) AS S
ON D.SYMBOL = S.SYMBOL
WHEN NOT MATCHED THEN 
    INSERT (SECURITY_ID, SYMBOL)
    VALUES (S.EXPECTED_ID, S.SYMBOL);


MERGE INTO DM_DIM.DIM_DATE d
USING (
  SELECT DISTINCT
    TO_NUMBER(TO_CHAR(e.TRADE_DATE, 'YYYYMMDD')) AS DATE_SK,
    e.TRADE_DATE                                 AS CAL_DATE,
    EXTRACT(YEAR    FROM e.TRADE_DATE)           AS YEAR_NUM,
    EXTRACT(QUARTER FROM e.TRADE_DATE)           AS QUARTER_NUM,
    EXTRACT(MONTH   FROM e.TRADE_DATE)           AS MONTH_NUM,
    MONTHNAME(e.TRADE_DATE)                     AS MONTH_NAME,
    EXTRACT(DAY     FROM e.TRADE_DATE)           AS DAY_NUM,
    DAYNAME(e.TRADE_DATE)                       AS DAY_NAME,
    EXTRACT(DAYOFWEEK FROM e.TRADE_DATE)         AS DAY_OF_WEEK,   -- 0=Sun in some DBs; Snowflake: 0=Sunday. Adjust if you prefer 1=Mon.
    EXTRACT(WEEK    FROM e.TRADE_DATE)           AS WEEK_OF_YEAR,
    IFF(EXTRACT(DAYOFWEEK FROM e.TRADE_DATE) IN (0,6), TRUE, FALSE) AS IS_WEEKEND
  FROM CORE.EOD_PRICES e
  ORDER BY DATE_SK
) s
ON d.DATE_SK = s.DATE_SK
WHEN NOT MATCHED THEN
  INSERT (DATE_SK, CAL_DATE, YEAR_NUM, QUARTER_NUM, MONTH_NUM, MONTH_NAME, DAY_NUM, DAY_NAME, DAY_OF_WEEK, WEEK_OF_YEAR, IS_WEEKEND)
  VALUES (s.DATE_SK, s.CAL_DATE, s.YEAR_NUM, s.QUARTER_NUM, s.MONTH_NUM, s.MONTH_NAME, s.DAY_NUM, s.DAY_NAME ,s.DAY_OF_WEEK, s.WEEK_OF_YEAR, s.IS_WEEKEND);

MERGE INTO DM.FACT.FACT_DAILY_PRICE
SELECT 
    DS.SECURITY_ID,
    TO_NUMBER(TO_CHAR(E.TRADE_DATE, 'YYYYMMDD')) AS DATE_SK,
    E.TRADE_DATE,
    E.OPEN,
    E.HIGH,
    E.LOW,
    E.CLOSE,
    E.VOLUME
FROM CORE.EOD_PRICES AS E
JOIN DM_DIM.DIM_SECURITY AS DS ON DS.SYMBOL = E.SYMBOL
JOIN DM_DIM.DIM_DATE AS DE ON DE.DATE_SK = TO_NUMBER(TO_CHAR(E.TRADE_DATE, 'YYYYMMDD'));




MERGE INTO DM_DIM.DIM_SECURITY d
USING (
    SELECT
        SYMBOL,
        ROW_NUMBER() OVER (ORDER BY SYMBOL) as EXPECTED_ID
    FROM (
        SELECT DISTINCT SYMBOL
        FROM CORE.EOD_PRICES
    )
) s
ON d.SYMBOL = s.SYMBOL
WHEN NOT MATCHED THEN
    INSERT (SECURITY_ID, SYMBOL)
    VALUES (s.EXPECTED_ID, s.SYMBOL);





MERGE INTO DM_FACT.FACT_DAILY_PRICE f
USING (SELECT
    ds.SECURITY_ID,
    TO_NUMBER(TO_CHAR(e.TRADE_DATE, 'YYYYMMDD')) AS DATE_SK,
    e.TRADE_DATE,
    e.OPEN,
    e.HIGH,
    e.LOW,
    e.CLOSE,
    e.VOLUME
FROM CORE.EOD_PRICES e
JOIN DM_DIM.DIM_SECURITY ds ON ds.SYMBOL = e.SYMBOL
JOIN DM_DIM.DIM_DATE dd ON dd.DATE_SK = TO_NUMBER(TO_CHAR(e.TRADE_DATE, 'YYYYMMDD'))
) src
ON f.SECURITY_ID = src.SECURITY_ID AND f.DATE_SK = src.DATE_SK
WHEN MATCHED THEN UPDATE SET
  TRADE_DATE = src.TRADE_DATE,
  OPEN = src.OPEN,
  HIGH = src.HIGH,
  LOW = src.LOW,
  CLOSE = src.CLOSE,
  VOLUME = src.VOLUME,
  LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  SECURITY_ID, DATE_SK, TRADE_DATE, OPEN, HIGH, LOW, CLOSE, VOLUME, LOAD_TS
) VALUES (
  src.SECURITY_ID, src.DATE_SK, src.TRADE_DATE, src.OPEN, src.HIGH, src.LOW,
  src.CLOSE, src.VOLUME, CURRENT_TIMESTAMP()
);



