USE WAREHOUSE WH_INGEST;
USE DATABASE SEC_PRICING;


-- Purpose: Define a reusable CSV file format to interpret staged files.
-- FILE FORMAT CONFIGURATION
CREATE OR REPLACE FILE FORMAT SEC_PRICING.RAW.CSV_EOD
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL');








CREATE OR REPLACE STORAGE INTEGRATION INT_S3_AIRFLOWSNOWDE
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::211125561737:role/rbf-daily-neeraj'
  STORAGE_ALLOWED_LOCATIONS = ('s3://rbf-stocks-daily-s3/market/bronze/');


DESC INTEGRATION INT_S3_AIRFLOWSNOWDE;


CREATE OR REPLACE STAGE SEC_PRICING.RAW.EXT_BRONZE
  URL = 's3://rbf-stocks-daily-s3/market/bronze/'
  STORAGE_INTEGRATION = INT_S3_AIRFLOWSNOWDE;


  DESC STAGE SEC_PRICING.RAW.EXT_BRONZE;



LIST @SEC_PRICING.RAW.EXT_BRONZE;